#!/usr/bin/env python3
"""
从 TTF/OTF 生成 LVGL 8 用的 4bpp 点阵字体（C 文件）。

为什么需要它：LVGL 内置的 lv_font_simsun_16_cjk 只带 146 个汉字，界面上大部分中文
都会渲染成方框。用这个脚本可以从任意改字体生成"刚好够用"的字库。

用法示例：
    python gen_lvgl_font.py \
        --font NotoSansSC-Regular.otf \
        --size 16 --name lv_font_noto_sc_16 \
        --extra-scan ../main \
        --out ../main/fonts/lv_font_noto_sc_16.c

默认字表 = ASCII 可见字符 + GB2312 一级字库(3755 字) + 扫描源码里出现的所有非 ASCII 字符。
生成格式与 lv_font_conv 一致：4bpp、行间不补齐、每字节高半字节存左边的像素。
"""

import argparse
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

# 中文标点与常见符号（GB2312 一级字表里没有这些，单独补上）
DEFAULT_PUNCTUATION = "，。、；：？！（）《》【】“”‘’—…·～￥％＋－×÷°"


def gb2312_level1_chars():
    """GB2312 一级汉字（常用字，3755 个）"""
    chars = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return chars


def scan_extra_chars(paths):
    """扫描源码中出现过的所有非 ASCII 字符，保证界面文字一定有字形"""
    found = set()
    for path in paths:
        if os.path.isfile(path):
            files = [path]
        else:
            files = []
            for root, _dirs, names in os.walk(path):
                files += [os.path.join(root, n) for n in names
                          if n.endswith((".c", ".h", ".cpp", ".txt", ".md"))]
        for f in files:
            try:
                text = open(f, encoding="utf-8", errors="ignore").read()
            except OSError:
                continue
            for ch in text:
                if ord(ch) > 0x7F:
                    found.add(ch)
    return found


def build_charset(font, extra_paths, extra_chars, only_chars=""):
    if only_chars:
        chars = set(only_chars)
        # 只保留字体里真的有的字符
        return [c for c in sorted(chars, key=ord) if _has_glyph(font, c)], []
    chars = set(chr(c) for c in range(0x20, 0x7F))
    for ch in gb2312_level1_chars():
        chars.add(ch)
    for ch in DEFAULT_PUNCTUATION:
        chars.add(ch)
    for ch in extra_chars:
        chars.add(ch)
    chars |= scan_extra_chars(extra_paths)

    # 只保留字体里真的有的字符
    kept, dropped = [], []
    for ch in sorted(chars, key=ord):
        (kept if _has_glyph(font, ch) else dropped).append(ch)
    return kept, dropped


def _has_glyph(font, ch):
    try:
        # 没有墨迹的字符（空格等）也要保留，靠 advance 参与排版
        return font.getmask(ch).getbbox() is not None or ch == " "
    except Exception:
        return False


def render_glyph(font, ch, size, ascent):
    """返回 (bitmap_rows, box_w, box_h, ofs_x, ofs_y)"""
    pad = size
    canvas = Image.new("L", (size * 3, size * 3), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((pad, pad + ascent), ch, font=font, fill=255, anchor="ls")
    bbox = canvas.getbbox()
    if bbox is None:
        return None, 0, 0, 0, 0

    x0, y0, x1, y1 = bbox
    box_w, box_h = x1 - x0, y1 - y0
    ofs_x = x0 - pad
    # 墨迹顶端相对"升部顶端"的偏移
    top_from_ascender = y0 - pad
    ofs_y = ascent - top_from_ascender - box_h
    return canvas.crop(bbox), box_w, box_h, ofs_x, ofs_y


def pack_4bpp(img):
    """4bpp 紧凑打包，每字节高半字节在前"""
    w, h = img.size
    px = img.load()
    out = bytearray()
    cur = 0
    nibbles = 0
    for y in range(h):
        for x in range(w):
            v = px[x, y] >> 4          # 8bit -> 4bit
            if nibbles == 0:
                cur = v << 4
                nibbles = 1
            else:
                out.append(cur | v)
                nibbles = 0
    if nibbles:
        out.append(cur)
    return bytes(out)


def emit_c(out_path, name, size, line_height, base_line, glyphs, cmaps):
    guard = name.upper()
    lines = []
    w = lines.append

    w("/*******************************************************************************")
    w(" * Size: %d px" % size)
    w(" * Bpp: 4")
    w(" * Generated by tools/gen_lvgl_font.py - do not edit by hand.")
    w(" ******************************************************************************/")
    w("")
    w('#include "lvgl.h"')
    w("")
    w("#ifndef %s" % guard)
    w("    #define %s 1" % guard)
    w("#endif")
    w("")
    w("#if %s" % guard)
    w("")
    w("/*-----------------")
    w(" *    BITMAPS")
    w(" *----------------*/")
    w("")
    w("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    for g in glyphs:
        w('    /* U+%04X */' % g["cp"])
        data = g["bitmap"]
        for i in range(0, len(data), 16):
            w("    " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    w("};")
    w("")
    w("/*-----------------")
    w(" *  GLYPH DESCRIPTIONS")
    w(" *----------------*/")
    w("")
    w("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    for g in glyphs:
        w("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
          % (g["bitmap_index"], g["adv_w"], g["box_w"], g["box_h"], g["ofs_x"], g["ofs_y"]))
    w("};")
    w("")
    # 注意：LVGL 的 unicode_list 是 uint16_t 数组（见 lv_font_fmt_txt.h），
    # 写成 uint32_t 会导致查表时字节错位、所有非 ASCII 字符都找不到字形。
    w("static const uint16_t unicode_list_1[] = {")
    ul = cmaps["sparse_list"]
    for i in range(0, len(ul), 10):
        w("    " + ", ".join("0x%04x" % v for v in ul[i:i + 10]) + ",")
    w("};")
    w("")
    w("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    w("    {")
    if cmaps["ascii_count"] == 95:
        w("        .range_start = 32, .range_length = 95, .glyph_id_start = 1,")
    else:
        # 纯数字/符号小字体：不设连续 ASCII 段，全部走下面的稀疏表
        w("        .range_start = 0, .range_length = 0, .glyph_id_start = 1,")
    w("        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,")
    w("        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY")
    w("    },")
    w("    {")
    w("        .range_start = %d, .range_length = %d, .glyph_id_start = %d,"
      % (cmaps["sparse_start"], cmaps["sparse_len"], cmaps["sparse_gid_start"]))
    w("        .unicode_list = unicode_list_1, .glyph_id_ofs_list = NULL, .list_length = %d,"
      % len(ul))
    w("        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY")
    w("    }")
    w("};")
    w("")
    w("/*-----------------")
    w(" *  FONT DESCRIPTOR")
    w(" *----------------*/")
    w("")
    w("static lv_font_fmt_txt_glyph_cache_t cache;")
    w("")
    w("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    w("    .glyph_bitmap = glyph_bitmap,")
    w("    .glyph_dsc = glyph_dsc,")
    w("    .cmaps = cmaps,")
    w("    .kern_dsc = NULL,")
    w("    .kern_scale = 16,")
    w("    .cmap_num = 2,")
    w("    .bpp = 4,")
    w("    .kern_classes = 0,")
    w("    .bitmap_format = 0,")
    w("    .cache = &cache")
    w("};")
    w("")
    w("/*-----------------")
    w(" *  PUBLIC FONT")
    w(" *----------------*/")
    w("")
    w("const lv_font_t %s = {" % name)
    w("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    w("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    w("    .line_height = %d," % line_height)
    w("    .base_line = %d," % base_line)
    w("    .subpx = LV_FONT_SUBPX_NONE,")
    w("    .underline_position = -2,")
    w("    .underline_thickness = 1,")
    w("    .dsc = &font_dsc,")
    w("    .fallback = NULL,")
    w("};")
    w("")
    w("#endif /*%s*/" % guard)
    w("")

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="ascii", errors="replace", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", required=True, help="TTF/OTF 字体文件")
    ap.add_argument("--size", type=int, default=16, help="像素高度")
    ap.add_argument("--name", required=True, help="生成的 lv_font_t 变量名")
    ap.add_argument("--out", required=True, help="输出的 .c 文件")
    ap.add_argument("--extra-scan", action="append", default=[],
                    help="额外扫描的源码目录/文件（把这些文件里出现的汉字也加进字库）")
    ap.add_argument("--extra-chars", default="", help="额外补充的字符")
    ap.add_argument("--only-chars", default="",
                    help="只用这些字符（忽略默认的 ASCII+GB2312 字表，用于生成数字/符号小字体）")
    ap.add_argument("--line-height", type=int, default=0,
                    help="覆盖行高（默认用字体的 ascent+descent；数字小字体可以调紧，省版面）")
    args = ap.parse_args()

    font = ImageFont.truetype(args.font, args.size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent
    if args.line_height:
        if args.line_height < descent + 4:
            raise SystemExit("行高 %d 太小（至少要 descent+4 = %d），字形会超出行框"
                             % (args.line_height, descent + 4))
        line_height = args.line_height

    chars, dropped = build_charset(font, args.extra_scan, args.extra_chars, args.only_chars)
    print("字体: %s  字号: %dpx  行高: %d (ascent=%d descent=%d)"
          % (os.path.basename(args.font), args.size, line_height, ascent, descent))
    print("收录字形: %d 个（跳过字体中不存在的 %d 个）" % (len(chars), len(dropped)))
    if dropped[:10]:
        print("  跳过示例: %s" % "".join(dropped[:10]))

    # 0 号字形是"找不到字形"时的占位
    glyphs = [{"cp": 0, "comment": "placeholder", "bitmap": b"", "bitmap_index": 0,
               "adv_w": args.size * 8, "box_w": 0, "box_h": 0, "ofs_x": 0, "ofs_y": 0}]

    if args.only_chars:
        # 小字体模式：所有字形都放进稀疏表，顺序 = 码位升序
        ascii_chars = []
        other_chars = sorted(chars, key=ord)
    else:
        ascii_chars = [c for c in chars if 0x20 <= ord(c) <= 0x7E]
        other_chars = [c for c in chars if ord(c) > 0x7E]

        # cmap 0 假定 ASCII 0x20..0x7E 是连续的 95 个字形，顺序不能少
        if len(ascii_chars) != 95:
            raise SystemExit("ASCII 字形数量异常: %d（应为 95），请检查字体或字表过滤逻辑"
                             % len(ascii_chars))

    bitmap_offset = 0
    ordered = ascii_chars + other_chars
    for ch in ordered:
        img, box_w, box_h, ofs_x, ofs_y = render_glyph(font, ch, args.size, ascent)
        adv_w = int(round(font.getlength(ch) * 16))
        data = pack_4bpp(img) if img is not None else b""
        glyphs.append({
            "cp": ord(ch), "comment": "" if ord(ch) < 32 else ch,
            "bitmap": data, "bitmap_index": bitmap_offset,
            "adv_w": adv_w, "box_w": box_w, "box_h": box_h,
            "ofs_x": ofs_x, "ofs_y": ofs_y,
        })
        bitmap_offset += len(data)

    sparse_list = [ord(c) - 32 for c in other_chars]  # 相对 range_start 的偏移
    if sparse_list and max(sparse_list) > 0xFFFF:
        raise SystemExit(
            "稀疏表偏移 %d 超过 uint16_t 上限：字表里出现了 U+%04X 这类过大的码位，"
            "请把 cmaps 里的 range_start 调整到更接近实际用字范围后重新生成"
            % (max(sparse_list), max(ord(c) for c in other_chars)))
    cmaps = {
        "sparse_start": 32,
        "sparse_len": (max(sparse_list) if sparse_list else 0) + 1,
        "sparse_gid_start": 1 + len(ascii_chars),
        "sparse_list": sparse_list,
        "ascii_count": len(ascii_chars),
    }

    emit_c(args.out, args.name, args.size, line_height, descent, glyphs, cmaps)
    total = sum(len(g["bitmap"]) for g in glyphs)
    print("位图数据: %.1f KB   输出: %s" % (total / 1024.0, args.out))
    print("提示：生成的 C 文件里请同时确认 line_height=%d, base_line=%d"
          % (line_height, descent))
    return 0


if __name__ == "__main__":
    sys.exit(main())
