idf_component_register(SRCS "wifi_mqtt.c" "gateway_main.c"
                            "display.c" "board.c" "ui.c" "gw_log.c" "gw_hist.c"
                            "gw_buzzer.c" "gw_cal.c"
                            "fonts/lv_font_noto_sc_16.c"
                            "fonts/lv_font_digit_22.c"
                       INCLUDE_DIRS ".")
